all: a

a : main.cpp
	g++ main.cpp parte1/artists.cpp parte1/tracks.cpp parte1/functeste.cpp parte2/Ordenacao.cpp parte2/tabelahash.cpp parte3/ArvoreVP.cpp parte3/ArvoreB.cpp -o main

DIR=""

run:a
	./main $(DIR)