all: a

a : main.cpp artists.cpp tracks.cpp functeste.cpp
	g++ main.cpp artists.cpp tracks.cpp functeste.cpp Ordenacao.cpp tabelahash.cpp ArvoreVP.cpp ArvoreB.cpp -o main

DIR=""

run:a
	./main $(DIR)